### ISSUE TITLE
Mindmap type diagram not supported?

### ISSUE THREAD

**Issue by dimonf** [RobertWeinmeister/dokuwiki-mermaid#14]
Looks like mindmap type diagram is not supported yet?

**Comment by RobertWeinmeister** [comment]
The diagram type mind map is supported. Do you have any problems with it?

**Comment by dimonf** [comment]
Yep, looks like this specific type is not rendered in my installation. As far as I can see, other types are ok, eg "jorney", "pie".
```
<mermaid>
mindmap
root(Z)
  item a
  item b
</mermaid>
```

**Comment by RobertWeinmeister** [comment]
Make sure you have the latest plugin version installed. Use at least version 9.4 of Mermaid.

If this still does not work, please post the result you get.

**Comment by dimonf** [comment]
I have the following settings:
plugin»mermaid»location:  remotely hosted, latest version (ESM)

I believe this setting defines version in use - I didn't explicitly install anything else.

**Comment by RobertWeinmeister** [comment]
Log in as an administrator, go to the [Extension Manager](https://www.dokuwiki.org/plugin:extension). Update the plugin there if possible. This should fix it.

**Comment by dimonf** [comment]
manually upgraded via `git clone`... manually downloaded mermaid.min.js into lib/plugins/mermaid/... No positive effect, unfortunately. I'll learn how to debug the code, and I'll try to find the source of the problem later myself. Thank you for your attention and excellent plugin, anyway.

**Comment by RobertWeinmeister** [comment]
If you manually loaded the Mermaid file, did you also change the setting to actually use it?

What do you currently get, just empty space? The example you gave works perfectly fine for me.

Otherwise, use the developer tools in your browser (F12) and have a look at the output there after reloading the page.

**Comment by dimonf** [comment]
1. I did
2. empty space
3. Thank you for the hint (I am not good with frontend JS apps). Looks like I have problem elsewhere.  Actually, I have at least one other plugin (tagadd) not working properly.
<details>
<summary>console error</summary>
jplayer.blue.monday.min.css:1     Failed to load resource: the server responded with a status of 403 (Forbidden)
jquery.jplayer.min.js:1     Failed to load resource: the server responded with a status of 403 (Forbidden)
jplayer.playlist.min.js:1     Failed to load resource: the server responded with a status of 403 (Forbidden)
js.php?t=dokuwiki&tseed=7d698ba9fa60469a75232317d2f5d9b7:1 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
(anonymous) @ js.php?t=dokuwiki&tseed=7d698ba9fa60469a75232317d2f5d9b7:1
jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2 jQuery.Deferred exception: jQuery(...).popover is not a function TypeError: jQuery(...).popover is not a function
    at HTMLDocument.<anonymous> (http://dwiki.lan/lib/exe/js.php?t=dokuwiki&tseed=7d698ba9fa60469a75232317d2f5d9b7:1:125766)
    at e (http://dwiki.lan/lib/exe/jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2:30158)
    at t (http://dwiki.lan/lib/exe/jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2:30460) undefined
S.Deferred.exceptionHook @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2 jQuery.Deferred exception: $mobileMenuOption.form is not a function TypeError: $mobileMenuOption.form is not a function
    at http://dwiki.lan/lib/exe/js.php?t=dokuwiki&tseed=7d698ba9fa60469a75232317d2f5d9b7:5:14565
    at HTMLDocument.<anonymous> (http://dwiki.lan/lib/exe/js.php?t=dokuwiki&tseed=7d698ba9fa60469a75232317d2f5d9b7:5:14787)
    at e (http://dwiki.lan/lib/exe/jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2:30158)
    at t (http://dwiki.lan/lib/exe/jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2:30460) undefined
S.Deferred.exceptionHook @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2 Uncaught TypeError: jQuery(...).popover is not a function
    at HTMLDocument.<anonymous> (js.php?t=dokuwiki&tseed=7d698ba9fa60469a75232317d2f5d9b7:1:125766)
    at e (jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2:30158)
    at t (jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2:30460)
jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2 Uncaught TypeError: $mobileMenuOption.form is not a function
    at js.php?t=dokuwiki&tseed=7d698ba9fa60469a75232317d2f5d9b7:5:14565
    at HTMLDocument.<anonymous> (js.php?t=dokuwiki&tseed=7d698ba9fa60469a75232317d2f5d9b7:5:14787)
    at e (jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2:30158)
    at t (jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2:30460)
mermaid.min.js:24 Uncaught Error: Parse error on line 1:
mindmaproot(Z)  it
^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
    at Vt.parseError (mermaid.min.js:24:98653)
    at Vt.parse (mermaid.min.js:24:99828)
    at Dt (mermaid.min.js:34:112811)
    at Object.render (mermaid.min.js:34:238677)
    at a (mermaid.min.js:41:223)
    at Object.init (mermaid.min.js:41:313)
    at Ba (mermaid.min.js:34:242305)
    at mermaid.min.js:38:44
jplayer.blue.monday.min.css:1     Failed to load resource: the server responded with a status of 403 (Forbidden)
DevTools failed to load source map: Could not load content for http://dwiki.lan/lib/plugins/flowcharts/mermaid.min.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

</details>

**Comment by RobertWeinmeister** [comment]
The log says you got a parse error. You can try out your code online with the [Mermaid Live Editor](https://mermaid.live/edit#pako:eNo9izEOwjAMRa8S_QmkniAzN2BDXkztQqTaqYIzoKp3b1jYnp7e2zFXUWRYcTHeyFutcXlcyVMqoZb4T09MMG3GRcaw_zwh3mpKyANFF-5rEMiPkXKPev_6jByt64S-CYfeCr8aG_LC60ePE8NeK3o). If it works there, it should (almost always) work with this plugin.
