### ISSUE TITLE
Binding click events in gantt chart

### ISSUE THREAD

**Issue by Ragos81** [RobertWeinmeister/dokuwiki-mermaid#26]
It would be nice to use the binding click events also in a gantt chart.

For example:
`[[thispage#installation_plan|Installation plan]]: p1, 2024-09-14, 1w`
Would refer to the headline **Installation plan** of **thispage**.

In general Mermaid has such a function (see [https://mermaid.js.org/syntax/gantt.html#interaction](https://mermaid.js.org/syntax/gantt.html#interaction)) and as described [here](https://www.dokuwiki.org/plugin:mermaid#binding_click_events) it works already for flowcharts in dokuwiki.

**Comment by RobertWeinmeister** [comment]
Good idea, I wrote a first implementation which should support all DokuWiki link types with Gantt charts now.

You can give it a try by replacing your file `dokuwiki/lib/plugins/mermaid/syntax.php` with this file `https://raw.githubusercontent.com/RobertWeinmeister/dokuwiki-mermaid/gantt-links/syntax.php` and see if it works as intended for you.

I will include it in the next update.

**Comment by Ragos81** [comment]
Great @RobertWeinmeister !
Will give it a try on Monday when I'm back to work!

**Comment by Ragos81** [comment]
@RobertWeinmeister 

I copied the file, but it seems nothing has changed.

this input
`[[:project:machine_installation#plant_layout|Plant layout]]Plant layout: plant_layout, 2024-09-14, 2024-09-25`

produces this output (same like before)
![image](https://github.com/user-attachments/assets/1948d6ae-1077-46ee-bc5a-9591fc1a1f4a)

**Comment by RobertWeinmeister** [comment]
Using your code
```
<mermaid>
gantt
  [[:project:machine_installation#plant_layout|Plant layout]]Plant layout: plant_layout, 2024-09-14, 2024-09-25
</mermaid>
```
I get:
![image](https://github.com/user-attachments/assets/901b6642-7878-4031-8232-9b60e10d90a0)


Maybe it showed the cached result. I will try to get the update out this weekend.

**Comment by Ragos81** [comment]
Maybe I didn't pay enough attention. I will purge the page and empty the browser cache tomorrow and try it again. Will let you know the result @RobertWeinmeister

**Comment by Ragos81** [comment]
I purged the page and emptied the browser cache, but it still looks like before. The log shows this error:

```
2024-09-25 00:33:25
E_WARNING: Undefined array key 0
/var/www/html/lib/plugins/mermaid/syntax.php(137)
#0 /var/www/html/lib/plugins/mermaid/syntax.php(137): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/inc/parser/renderer.php(126): syntax_plugin_mermaid->render()
#2 /var/www/html/inc/parserutils.php(691): Doku_Renderer->plugin()
#3 /var/www/html/inc/parserutils.php(158): p_render()
#4 /var/www/html/inc/parserutils.php(97): p_cached_output()
#5 /var/www/html/inc/Ui/PageView.php(67): p_wiki_xhtml()
#6 /var/www/html/inc/Action/Show.php(40): dokuwiki\Ui\PageView->show()
#7 /var/www/html/inc/template.php(120): dokuwiki\Action\Show->tplContent()
#8 [internal function]: tpl_content_core()
#9 /var/www/html/inc/Extension/Event.php(134): call_user_func_array()
#10 /var/www/html/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#11 /var/www/html/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
#12 /var/www/html/lib/tpl/dokuwiki/main.php(60): tpl_content()
#13 /var/www/html/inc/actions.php(30): include('...')
#14 /var/www/html/doku.php(131): act_dispatch()
#15 {main}
```

I don't know what's wrong. Could it be another plugin that cause the problem?
