### ISSUE TITLE
Save button triggers large amount of download instances of the same graph

### ISSUE THREAD

**Issue by amitlumiloop** [RobertWeinmeister/dokuwiki-mermaid#34]
**Description**
Title

**Mermaid code**
<mermaid>
graph LR
    A[Square Rect] -- Link text --> B((Circle))
    A --> C(Round Rect)
    B --> D{Rhombus}
    C --> D
</mermaid>

**Actual behaviour**
starts multiple downloads of the same file. In the magnitude of hundreds.

**Expected behaviour**
Download only once 

**Versions**
DokuWiki: Release 2024-02-06b "Kaos"
Plugin: 2024-10-15
Mermaid: remotely hosted, latest version (ESM)

**Comment by RobertWeinmeister** [comment]
I cannot replicate this. Which browser and OS are you using? The more specific the better.

**Comment by amitzionii** [comment]
Hey, 
Thank you for the answer. I use firefox on debian, so version 128.4.0esr-1~deb12u1. When I tried to inspect the save button with the firefox developer tools, it also open a long list with click events that point to the same place in the Javascript code. However I'm not very knowledgeable with javascript so I could'nt figure out why it fires the click event so many times instead of just once every click.

**Comment by RobertWeinmeister** [comment]
I tried it with this Firefox version too, but I only ever find one attached click event. Could you maybe disable any other DokuWiki plugins to see if there is an incompatibility?

The way it works is that the click event gets attached once Mermaid processed the contents. This is done by observing the element to see if Mermaid changed the inner content to the final svg. Only reason I could see is if there is another plugin interfering. I could make sure to check if there is another event listener already attached to prevent this, but this code should not be called that often regardless.

**Comment by amitlumiloop** [comment]
So the problem was really the old unmaintained mermaid plugin, called "flowchart plugin". When both plugins are activated the save button go crazy.  Maybe it is worth documenting it somewhere. Anyway thanks a lot for your time and effort :)
