### ISSUE TITLE
Mermaid renderer elk not working for ESM versions

### ISSUE THREAD

**Issue by Schmoaaaaah** [RobertWeinmeister/dokuwiki-mermaid#4]
## Versions:

- DokuWiki: JackJackrum
- mermaidplugin: 2023-04-05

## Problem

When using following config with mermaid versions greater then 9.4 selected in settings you get a syntax error.

```
%%{init: {'flowchart':{'curve':'linear','defaultRenderer':'elk'}}}%%
    flowchart TD
        A[Christmas] -->|Get money| B(Go shopping)
        B --> C{Let me think}
        C -->|One| D[Laptop]
        C -->|Two| E[iPhone]
        C -->|Three| F[fa:fa-car Car]
```

Am I doing something wrong or is it a Bug?

**Comment by Schmoaaaaah** [comment]
Ok thanks. So as far as i can tell it works with the 9.4 setting. Maybe something to do with the esm way of loading the new ones?

**Comment by RobertWeinmeister** [comment]
Oh yes, you are right. I looked a bit more into it. It works perfectly fine with the CJS versions and the locally hosted version. There seems to be a Mermaid internal problem with how this renderer is loaded with ESM. I'll see if I can clarify and fix the underlying problem.
